-- SQLite

DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS FILE;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS CONNECT_NOTE_FILE;
DROP TABLE IF EXISTS CONNECT_NOTE_TASK;

CREATE TABLE NOTE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    content TEXT,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE FILE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    content TEXT,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE TASK (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    content TEXT,
    created_at TEXT,
    updated_at TEXT,
    isCompleted INTEGER
);

CREATE TABLE CONNECT_NOTE_FILE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    note_id INTEGER,
    file_id INTEGER
);

CREATE TABLE CONNECT_NOTE_TASK (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    note_id INTEGER,
    task_id INTEGER
);
